# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ytpd_beta.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 498)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(180, 182, 182)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 0, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("color: rgb(252, 1, 7)")
        self.title_label.setText("Turbo YouTube Playlist Downloader")
        self.title_label.setObjectName("title_label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(520, 40, 281, 301))
        self.listWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.listWidget.setObjectName("listWidget")
        self.enter_playlist_url_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_playlist_url_label.setGeometry(QtCore.QRect(10, 70, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.enter_playlist_url_label.setFont(font)
        self.enter_playlist_url_label.setObjectName("enter_playlist_url_label")
        self.url_input = QtWidgets.QLineEdit(self.centralwidget)
        self.url_input.setGeometry(QtCore.QRect(140, 70, 301, 20))
        self.url_input.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.url_input.setObjectName("url_input")
        self.url_load_button = QtWidgets.QPushButton(self.centralwidget)
        self.url_load_button.setGeometry(QtCore.QRect(370, 100, 71, 23))
        self.url_load_button.setObjectName("url_load_button")
        self.remove_from_list_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_from_list_button.setGeometry(QtCore.QRect(670, 350, 131, 23))
        self.remove_from_list_button.setObjectName("remove_from_list_button")
        self.url_error_label = QtWidgets.QLabel(self.centralwidget)
        self.url_error_label.setGeometry(QtCore.QRect(140, 50, 271, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.url_error_label.setFont(font)
        self.url_error_label.setObjectName("url_error_label")
        self.url_fetching_data_label = QtWidgets.QLabel(self.centralwidget)
        self.url_fetching_data_label.setGeometry(QtCore.QRect(140, 102, 231, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.url_fetching_data_label.setFont(font)
        self.url_fetching_data_label.setObjectName("url_fetching_data_label")
        self.guide_label = QtWidgets.QLabel(self.centralwidget)
        self.guide_label.setGeometry(QtCore.QRect(10, 130, 451, 111))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.guide_label.setFont(font)
        self.guide_label.setObjectName("guide_label")
        self.listWidget_label = QtWidgets.QLabel(self.centralwidget)
        self.listWidget_label.setGeometry(QtCore.QRect(520, 20, 201, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.listWidget_label.setFont(font)
        self.listWidget_label.setObjectName("listWidget_label")
        self.download_button = QtWidgets.QPushButton(self.centralwidget)
        self.download_button.setGeometry(QtCore.QRect(12, 340, 91, 23))
        self.download_button.setObjectName("download_button")
        self.downloaded_label = QtWidgets.QLabel(self.centralwidget)
        self.downloaded_label.setGeometry(QtCore.QRect(10, 380, 131, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.downloaded_label.setFont(font)
        self.downloaded_label.setText("")
        self.downloaded_label.setObjectName("downloaded_label")
        self.credits_label = QtWidgets.QLabel(self.centralwidget)
        self.credits_label.setGeometry(QtCore.QRect(10, 420, 581, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.credits_label.setFont(font)
        self.credits_label.setObjectName("credits_label")
        self.turbo_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.turbo_enable.setGeometry(QtCore.QRect(120, 342, 62, 20))
        self.turbo_enable.setObjectName("turbo_enable")
        self.download_path = QtWidgets.QPushButton(self.centralwidget)
        self.download_path.setGeometry(QtCore.QRect(10, 251, 113, 32))
        self.download_path.setAutoDefault(False)
        self.download_path.setObjectName("download_path")
        self.download_folder_select = QtWidgets.QLabel(self.centralwidget)
        self.download_folder_select.setGeometry(QtCore.QRect(140, 255, 301, 21))
        self.download_folder_select.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.download_folder_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.download_folder_select.setFrameShadow(QtWidgets.QFrame.Plain)
        self.download_folder_select.setObjectName("download_folder_select")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enter_playlist_url_label.setText(_translate("MainWindow", "Enter playlist url:"))
        self.url_load_button.setText(_translate("MainWindow", "Load"))
        self.remove_from_list_button.setText(_translate("MainWindow", "Remove from list"))
        self.url_error_label.setText(_translate("MainWindow", "Could not retrieve URL. Try again."))
        self.url_fetching_data_label.setText(_translate("MainWindow", "Loading playlist..."))
        self.guide_label.setText(_translate("MainWindow", "Guide:\n"
"- Once the data from the url is loaded, video titles will be displayed in the box to the right.\n"
"- By selecting a video title and pressing the Remove from list button you can remove\n"
"  the vido from the download list.\n"
"- Then type in the folder name in wich the files will be downloaded.\n"
"- The download path is automaticly set to Desktop and can not be changed.\n"
"- To download the files click Download. "))
        self.listWidget_label.setText(_translate("MainWindow", "Playlist videos:"))
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.credits_label.setText(_translate("MainWindow", "Ira\'s turbo-downloader: https://github.com/irahorecka"))
        self.turbo_enable.setText(_translate("MainWindow", "Turbo"))
        self.download_path.setText(_translate("MainWindow", "Storage Folder"))
        self.download_folder_select.setText(_translate("MainWindow", "Folder: "))
